name: CI

on:
   push:
     paths:
       - 'release-versions/*'
   workflow_dispatch:


jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

       - name: Install Java
         uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
           java-version: '17'

       - name: Update the system
         run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt install curl grep

       - name: Build youtube
         run: |
          # curl -OL https://github.com/XDream8/revanced-creator/releases/download/keystores/revanced-creator.keystore
          # export additional_args="--keystore=revanced-creator.keystore"
          # export additional_args="-i theme -i -i general-ads video-ads-i remember-video-quality -i enable-wide-searchbar -i swipe-controls -i -i disable-fullscreen-panels client-spoof -i custom-playback-speed -i minimized-playback -i downloads -e hide-shorts-button -e seekbar-tapping -e custom-video-buffer -e -e premium-heading -e -e custom-branding -e enable-debugging -e settings -e old-quality-layout"
          sh -c "$(curl https://raw.githubusercontent.com/XDream8/revanced-creator/main/patch.sh)"
          curl -OL https://github.com/XDream8/revanced-creator/releases/download/youtube/vanced-microg.apk

       - name: Upload Build Artifact(youtube)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-mod
           path: |
            revanced-mod-*-non-root.apk
            vanced-microg.apk

       - name: Build youtube-music
         run: |
          # curl -OL https://github.com/XDream8/revanced-creator/releases/download/keystores/revanced-creator-music.keystore
          # export additional_args="--keystore=revanced-creator-music.keystore"
          export what_to_patch="youtube-music"
          sh -c "$(curl https://raw.githubusercontent.com/XDream8/revanced-creator/main/patch.sh)"

       - name: Upload Build Artifact(YouTube-Music)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-music
           path: revanced-music-*-non-root.apk

       - name: Build reddit
         run: |
          # curl -OL https://github.com/XDream8/revanced-creator/releases/download/keystores/revanced-creator-reddit.keystore
          # export additional_args="--keystore=revanced-creator-reddit.keystore"
          export what_to_patch="reddit"
          sh -c "$(curl https://raw.githubusercontent.com/XDream8/revanced-creator/main/patch.sh)"

       - name: Upload Build Artifact(Reddit)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-reddit
           path: revanced-reddit-*-non-root.apk

       - name: Build twitter
         run: |
          # curl -OL https://github.com/XDream8/revanced-creator/releases/download/keystores/revanced-creator-twitter.keystore
          # export additional_args="--keystore=revanced-creator-twitter.keystore"
          export what_to_patch="twitter"
          sh -c "$(curl https://raw.githubusercontent.com/XDream8/revanced-creator/main/patch.sh)"

       - name: Upload Build Artifact(Twitter)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-twitter
           path: revanced-twitter-*-non-root.apk

       - name: Build tiktok
         run: |
          export what_to_patch="tiktok"
          sh -c "$(curl https://raw.githubusercontent.com/XDream8/revanced-creator/main/patch.sh)"

       - name: Upload Build Artifact(TikTok)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-tiktok
           path: revanced-tiktok-*-non-root.apk

       - name: Build spotify
         run: |
          export what_to_patch="spotify"
          sh -c "$(curl https://raw.githubusercontent.com/XDream8/revanced-creator/main/patch.sh)"

       - name: Upload Build Artifact(Spotify)
         uses: actions/upload-artifact@v3
         with:
           name: revanced-spotify
           path: revanced-spotify-*-non-root.apk
